### ISSUE TITLE
Update Plugins

### ISSUE THREAD

**Issue by Lisiadito** [micro-editor/updated-plugins#5]
Hi, 
I wrote the [join-lines-plugin](https://github.com/Lisiadito/join-lines-plugin) and recently fixed some bugs. As I understand this repository is the source where all plugins are loaded from at the moment correct? Do you want me to open a PR for the changes on my plugin or what are the further plans with this repository as it seems to me to be temporary.

**Comment by zyedidia** [comment]
If you have updated your plugin, you can open a pull request on the plugin channel repo to point the URL back to your repo.json and I will merge that.

**Comment by Lisiadito** [comment]
Ok thanks will do that. Then this issue can be closed.

**Comment by Lisiadito** [comment]
Ah sorry I think there is misunderstanding. My plugin is already in the official plugin channel. But on the website it still shows the 1.0.0 version and the updated version 1.1.0 you published in this repository for micro 2.

**Comment by zyedidia** [comment]
On the plugin channel, the join lines plugin entry points to this repo. You can open a pull request to change it to point to your repo.

**Comment by Lisiadito** [comment]
Ok will do that. then the PR #7 can be closed.
